name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_PUBLISH_TOKEN }}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install and setup Scoop
        uses: MinoruSekine/setup-scoop@v4
        with:
          buckets: extras java

      - name: Cleanup Scoop install
        run: rm install.ps1

      - name: Run tests
        run: cargo test --verbose
      - name: Publish to crates.io
        run: cargo publish
